version: '3'

services:
  gpt4free:
    image: hlohaus789/g4f:latest
    shm_size: 2gb
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - '8089:8089'
      - '1337:1337'
      - '7900:7900'
    networks:
      kcgw8s0: null
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-kg480ss.entryPoints=http
      - 'traefik.http.routers.http-0-kg480ss.rule=Host(`gpt4free.limemarketing.online`) && PathPrefix(`/`)'
      - traefik.http.routers.http-0-kg480ss.service=http-0-kg480ss
      - traefik.http.routers.http-1-kg480ss.entryPoints=http
      - 'traefik.http.routers.http-1-kg480ss.rule=Host(`gpt4freeapi.limemarketing.online`) && PathPrefix(`/`)'
      - traefik.http.routers.http-1-kg480ss.service=http-1-kg480ss
      - traefik.http.routers.https-0-kg480ss.entryPoints=https
      - traefik.http.routers.https-0-kg480ss.middlewares=gzip
      - 'traefik.http.routers.https-0-kg480ss.rule=Host(`gpt4free.limemarketing.online`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-kg480ss.service=https-0-kg480ss
      - traefik.http.routers.https-0-kg480ss.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-kg480ss.tls=true
      - traefik.http.routers.https-1-kg480ss.entryPoints=https
      - traefik.http.routers.https-1-kg480ss.middlewares=gzip
      - 'traefik.http.routers.https-1-kg480ss.rule=Host(`gpt4freeapi.limemarketing.online`) && PathPrefix(`/`)'
      - traefik.http.routers.https-1-kg480ss.service=https-1-kg480ss
      - traefik.http.routers.https-1-kg480ss.tls.certresolver=letsencrypt
      - traefik.http.routers.https-1-kg480ss.tls=true
      - traefik.http.services.http-0-kg480ss.loadbalancer.server.port=8089
      - traefik.http.services.http-1-kg480ss.loadbalancer.server.port=1337
      - traefik.http.services.https-0-kg480ss.loadbalancer.server.port=8089
      - traefik.http.services.https-1-kg480ss.loadbalancer.server.port=1337
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 8089}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://gpt4free.limemarketing.online'
      - 'caddy_1.encode=zstd gzip'
      - 'caddy_1.handle_path.1_reverse_proxy={{upstreams 1337}}'
      - 'caddy_1.handle_path=/*'
      - caddy_1.header=-Server
      - 'caddy_1.try_files={path} /index.html /index.php'
      - 'caddy_1=https://gpt4freeapi.limemarketing.online'
      - caddy_ingress_network=kg480ss
      - coolify.managed=true
      - coolify.version=4.0.0-beta.239
      - coolify.applicationId=33
      - coolify.type=application
      - coolify.name=gpt4free-kcgw8s0-104059719729
      - coolify.pullRequestId=0
    restart: unless-stopped
    container_name: gpt4free-kcgw8s0-104059719729
volumes: {  }
networks:
  kcgw8s0:
    name: kcgw8s0
    external: true
